/*
 * Copyright 2016 Alessandro Falappa.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.alexfalappa.nbspringboot.templates.applproperties;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URI;

import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import org.netbeans.api.project.Project;
import org.netbeans.modules.maven.api.NbMavenProject;
import org.netbeans.spi.project.ui.templates.support.Templates;
import org.openide.WizardDescriptor;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;
import org.openide.util.Exceptions;

import static com.github.alexfalappa.nbspringboot.templates.applproperties.ApplConstants.WIZ_BASE_NAME;
import static com.github.alexfalappa.nbspringboot.templates.applproperties.ApplConstants.WIZ_PROFILE;

public final class ApplVisualPanel1 extends JPanel implements DocumentListener {

    private final ApplWizardPanel1 panel;
    private File resourceFolder = new File(System.getProperty("user.dir"));

    @SuppressWarnings("LeakingThisInConstructor")
    public ApplVisualPanel1(ApplWizardPanel1 panel) {
        initComponents();
        this.panel = panel;
        // Register listener on the textFields to make the automatic updates
        txBaseName.getDocument().addDocumentListener(this);
        txProfile.getDocument().addDocumentListener(this);
    }

    File getCreatedFile() {
        return FileUtil.normalizeFile(new File(txCreated.getText()).getAbsoluteFile());
    }

    void store(WizardDescriptor wd) {
        String baseName = txBaseName.getText().trim();
        String profile = txProfile.getText().trim();
        wd.putProperty(WIZ_BASE_NAME, baseName);
        wd.putProperty(WIZ_PROFILE, profile);
    }

    void read(WizardDescriptor wd) {
        final Project project = Templates.getProject(wd);
        if (project != null) {
            NbMavenProject nbProj = project.getLookup().lookup(NbMavenProject.class);
            if (nbProj != null) {
                final URI[] resources = nbProj.getResources(false);
                if (resources.length > 0) {
                    try {
                        resourceFolder = FileUtil.archiveOrDirForURL(resources[0].toURL());
                    } catch (MalformedURLException ex) {
                        Exceptions.printStackTrace(ex);
                    }
                }
            }
        }
        String baseName = (String) wd.getProperty(WIZ_BASE_NAME);
        if (baseName == null) {
            baseName = "application";
        }
        this.txBaseName.setText(baseName);
        this.txBaseName.selectAll();
        this.txProfile.setText((String) wd.getProperty(WIZ_PROFILE));
    }

    /** This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lBaseName = new javax.swing.JLabel();
        txBaseName = new javax.swing.JTextField();
        lProfile = new javax.swing.JLabel();
        txProfile = new javax.swing.JTextField();
        chConfigSubd = new javax.swing.JCheckBox();
        lCreated = new javax.swing.JLabel();
        txCreated = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(lBaseName, org.openide.util.NbBundle.getBundle(ApplVisualPanel1.class).getString("ApplVisualPanel1.lBaseName.text")); // NOI18N

        txBaseName.setColumns(15);

        org.openide.awt.Mnemonics.setLocalizedText(lProfile, org.openide.util.NbBundle.getBundle(ApplVisualPanel1.class).getString("ApplVisualPanel1.lProfile.text")); // NOI18N

        txProfile.setColumns(15);

        org.openide.awt.Mnemonics.setLocalizedText(chConfigSubd, org.openide.util.NbBundle.getBundle(ApplVisualPanel1.class).getString("ApplVisualPanel1.chConfigSubd.text")); // NOI18N
        chConfigSubd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chConfigSubdActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lCreated, org.openide.util.NbBundle.getBundle(ApplVisualPanel1.class).getString("ApplVisualPanel1.lCreated.text")); // NOI18N

        txCreated.setEditable(false);
        txCreated.setColumns(15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lBaseName)
                    .addComponent(lProfile)
                    .addComponent(lCreated))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txBaseName)
                    .addComponent(txProfile)
                    .addComponent(txCreated)
                    .addComponent(chConfigSubd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBaseName)
                    .addComponent(txBaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lProfile)
                    .addComponent(txProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chConfigSubd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCreated)
                    .addComponent(txCreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chConfigSubdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chConfigSubdActionPerformed
        updateTexts();
    }//GEN-LAST:event_chConfigSubdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chConfigSubd;
    private javax.swing.JLabel lBaseName;
    private javax.swing.JLabel lCreated;
    private javax.swing.JLabel lProfile;
    private javax.swing.JTextField txBaseName;
    private javax.swing.JTextField txCreated;
    private javax.swing.JTextField txProfile;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
        updateTexts();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        updateTexts();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        updateTexts();
    }

    // Handles changes in the base name and profile
    private void updateTexts() {
        // Change in the project name
        String baseName = txBaseName.getText();
        String profile = txProfile.getText();
        StringBuilder sb = new StringBuilder(resourceFolder.getAbsolutePath());
        sb.append(File.separatorChar);
        if (chConfigSubd.isSelected()) {
            sb.append("config").append(File.separatorChar);
        }
        sb.append(baseName);
        if (!profile.isEmpty()) {
            sb.append('-').append(profile);
        }
        sb.append(".properties");
        txCreated.setText(sb.toString());
        // Notify that the panel changed
        panel.fireChangeEvent();
    }

    boolean valid(WizardDescriptor wizardDescriptor) {
        if (txBaseName.getText().isEmpty()) {
            // Base name not specified
            wizardDescriptor.putProperty(WizardDescriptor.PROP_ERROR_MESSAGE, "Base name cannot be empty!");
            return false;
        }
        File f = getCreatedFile();
        if (f.exists()) {
            // Existing file
            wizardDescriptor.putProperty(WizardDescriptor.PROP_ERROR_MESSAGE, "Application properties file exists!");
            return false;
        }
        wizardDescriptor.putProperty(WizardDescriptor.PROP_ERROR_MESSAGE, "");
        final FileObject targetFolder = FileUtil.toFileObject(f.getParentFile());
        Templates.setTargetFolder(wizardDescriptor, targetFolder);
        Templates.setTargetName(wizardDescriptor, f.getName());
        return true;
    }

}
